### ISSUE TITLE
New option for making only HEAD requests (or ignoring 3xx redirects)

### ISSUE THREAD

**Issue by guihkx** [lilydjwg/nvchecker#175]
Hi,

I'm trying to add an update checker for this URL:

`https://www.unifiedremote.com/download/linux-x64-deb`

If you open that link, it will redirect you to the latest deb package of their software, e.g.:

`https://www.unifiedremote.com/static/builds/server/linux-x64/2465/urserver-3.9.0.2465.deb`

Obviously, I only want the `3.9.0.2465` part of the URL, but as far as I'm aware, there's currently no way to tell nvchecker to make a `HEAD` request, or even ignore 3xx HTTP redirects.

As a workaround, I'm using this ugly solution:

```toml
[UnifiedRemoteServer]
source = "cmd"
cmd = "curl -sI 'https://www.unifiedremote.com/download/linux-x64-deb' | grep -Fi 'Location:' | sed -r 's/.*?urserver-([0-9.]+)\\.deb/\\1/mi'"
```

Thoughts?
Thanks!

**Comment by aminvakil** [comment]
FWIW, I've changed a config file of mine to do this exactly.

https://github.com/aminvakil/nvchecker/commit/404cb13e16c721422b75680c856c41c4c562284c

This could help me as well.

**Comment by lilydjwg** [comment]
A new source has been added, see https://nvchecker.readthedocs.io/en/latest/usage.html#search-in-an-http-header.

**Comment by guihkx** [comment]
Wow, thanks for implementing this so quickly! Just tested it, works like a charm!

```toml
[UnifiedRemoteServer]
source = "httpheader"
regex = "urserver-([0-9.]+)\\.deb$"
url = "https://www.unifiedremote.com/download/linux-x64-deb"
```

And much more elegant! Feel free to close this now :)
