### ISSUE TITLE
Version transformation not working

### ISSUE THREAD

**Issue by grawlinson** [lilydjwg/nvchecker#204]
The version string transformation example in the bottom of [Global Options](https://nvchecker.readthedocs.io/en/latest/usage.html#global-options) does not seem to work, possibly because of the ini to toml configuration changes.

When using the example as is:

```toml
[example]
# other config
from_pattern = v(\d+)_(\d+)_(\d+)
to_pattern = \1.\2.\3.
```

returns `failed to load version configuration file '.repo/nvchecker.toml': This float doesn't have a leading digit (line 85 column 1 char 1244)`

When `from_pattern` and `to_pattern` are quoted, it still fails with `failed to load version configuration file '.repo/nvchecker.toml': Reserved escape sequence used (line 85 column 1 char 1244)`

And when attempting to escape the backslashes with another backslash, it returns the version number as `0`.

**Comment by lilydjwg** [comment]
In TOML strings are always quoted, so it should be

```toml
[example]
source = "cmd"
cmd = "echo v1_2_3"
from_pattern = 'v(\d+)_(\d+)_(\d+)'
to_pattern = '\1.\2.\3'
```

I've updated the doc.

I don't know why it returns `0`. It works for me.
