### ISSUE TITLE
Support RSS feeds as a source

### ISSUE THREAD

**Issue by skwerlman** [lilydjwg/nvchecker#289]
Some projects use RSS feeds as the main way of announcing new versions of their software. An example I use is proxmox-ve: https://my.proxmox.com/en/announcements/tag/proxmox-ve/rss

It would be nice if nvchecker had built-in support for reading RSS feeds to get the latest version info.

**Comment by lilydjwg** [comment]
This works:

```toml
[ProxmoxVE]
source = "htmlparser"
url = "https://my.proxmox.com/en/announcements/tag/proxmox-ve/rss"
xpath = "//item/title"
from_pattern = 'Proxmox VE ([\d.]+) released!'
to_pattern = '\1'
```

Although "htmlparser" is for HTML, it could often work with XML.
