### ISSUE TITLE
Dynamic oldver

### ISSUE THREAD

**Issue by allddd** [lilydjwg/nvchecker#303]
It would be nice if `oldver` could be dynamic, either by `nvchecker` updating it automatically or `nvcmp` reading it from a command defined in the config instead of from a static file.

This would make it easier to check versions for software installed on the system without needing to run `nvtake` manually after every update.

E.g.:

```toml
[__config__]
oldver = old_ver.json
newver = new_ver.json

[software-not-installed-locally]
github = user/repo
use_latest_release = true

[software-installed-locally]
github = user/repo
use_latest_release = true
# Get oldver from command output
oldvercmd = software-installed-locally --version
```

Would something like this be possible without making major changes to the codebase?
